### ISSUE TITLE
How I can get prefix size?

### ISSUE THREAD

**Issue by Damasker** [ribbybibby/s3_exporter#10]
I have this config:
- job_name: 's3-backup'
    metrics_path: /probe
    static_configs:
      - targets:
        - bucket=c-admin;prefix=backups/conr/mysql/;
        - bucket=c-admin;prefix=backups/conr/dse/;
        - bucket=c-admin;prefix=backups/conr/opscenter;
        - bucket=c-admin;prefix=backups/conr/redis;
        - bucket=c-admin;prefix=backups/conr/redis-local;
        - bucket=c-admin;prefix=backups/conr/mysql-local;
        - bucket=c-admin;prefix=backups/conr/scripts-windows;
        - bucket=c-admin;prefix=backups/conr/webroot-iis;
        - bucket=c-admin;prefix=backups/conr/windows-server;
    relabel_configs:
      - source_labels: [__address__]
        regex: '^bucket=(.*);prefix=(.*);$'
        replacement: '${1}'
        target_label: '__param_bucket'
      - source_labels: [__address__]
        regex: '^bucket=(.*);prefix=(.*);$'
        replacement: '${2}'
        target_label: '__param_prefix'
      - target_label: __address__
        replacement: 127.0.0.1:9340

I want get folder(prefix) size, instead of some file. This config correct?

**Comment by ribbybibby** [comment]
If I understand you correctly, you want to get the total size of all the objects returned by a particular prefix? If that's the case then `s3_objects_size_sum_bytes` should give you that.

**Comment by Damasker** [comment]
Yes, _s3_objects_size_sum_bytes_ give me what I want. 
Thank you!

**Comment by ribbybibby** [comment]
Great!
