### ISSUE TITLE
verbose Logs

### ISSUE THREAD

**Issue by hbo88** [ribbybibby/s3_exporter#23]
Hello ,

thank you for this project. 

i'm just testing the exporter on k8s the logs showed : 

`time="2021-04-22T20:58:16Z" level=info msg="Starting s3_exporter (version=0.4.0, branch=tags/v0.4.0, revision=4ecf1c121b7c4e4f1ee6c82aa0aee33ef028a081)" source="s3_exporter.go:190"

time="2021-04-22T20:58:16Z" level=info msg="Build context (go=go1.15.3, user=root@6f41cb83a3e1, date=20201018-15:45:51)" source="s3_exporter.go:191"

time="2021-04-22T20:58:16Z" level=info msg="Listening on :9340" source="s3_exporter.go:208"`

but I'm not getting any metrics from my S3 bucket.

Is there a way to activate some Debugs logs to Know what is the issue?

Many thanx

**Comment by ribbybibby** [comment]
You should be able to set the log level with `--log.level="debug"` in the [latest release](https://github.com/ribbybibby/s3_exporter/releases/tag/v0.4.1).
