### ISSUE TITLE
Getting nosuchbucket error , I am not able to find the option the give the s3 bucket name ?

### ISSUE THREAD

**Issue by kamuops** [ribbybibby/s3_exporter#24]
time="2021-04-25T13:47:39Z" level=info msg="Starting s3_exporter (version=0.4.0, branch=tags/v0.4.0, revision=4ecf1c121b7c4e4f1ee6c82aa0aee33ef028a081)" source="s3_exporter.go:190"
time="2021-04-25T13:47:39Z" level=info msg="Build context (go=go1.15.3, user=root@6f41cb83a3e1, date=20201018-15:45:51)" source="s3_exporter.go:191"
time="2021-04-25T13:47:39Z" level=info msg="Listening on :9340" source="s3_exporter.go:208"
time="2021-04-25T13:48:13Z" level=error msg="NoSuchBucket: The specified bucket does not exist\n\tstatus code: 404, request id: 3SDTXM7EGD1ATPPW, host id: HLqhGGWA0wUVBz/eMVruHiZhcQZmoE42C4QYLukqT4uqlIey03N01nZC9oJyQQ5/ujwbJQK1amc=" source="s3_exporter.go:92"

**Comment by ribbybibby** [comment]
There is an example of a curl command [in the README](https://github.com/ribbybibby/s3_exporter#running) that demonstrates how to provide the bucket name via query params.

See the [configuration](https://github.com/ribbybibby/s3_exporter#configuration) section for an example of how to scrape this exporter with Prometheus.

**Comment by kamuops** [comment]
Thank you @ribbybibby , I am good now.
