### ISSUE TITLE
Docker image for v0.5.0

### ISSUE THREAD

**Issue by calvinbui** [ribbybibby/s3_exporter#32]
The docker image for v0.5.0 hasn't been created yet at https://hub.docker.com/r/ribbybibby/s3-exporter

**Comment by ribbybibby** [comment]
Thanks for pointing this out! I was relying on automated builds in Docker Hub but it looks like they've been removed from the free tier. I'll move the docker build to GH actions.

In the meantime I've manually pushed the image up.
