### ISSUE TITLE
MissingRegion: could not find region configuration

### ISSUE THREAD

**Issue by ravi-visionet** [ribbybibby/s3_exporter#35]
Hi,

When I try to discover s3 buckets using "curl http://127.0.0.1:9340/discovery", getting below error.

<img width="919" alt="Error" src="https://user-images.githubusercontent.com/88369717/141238822-3928caf2-84c2-4fdd-a097-aa8e778ed959.PNG">

Could you please help here.

Note: I have permission to list s3 buckets using aws s3 ls.

**Comment by ribbybibby** [comment]
I missed this issue, apologies. You need to configure the AWS region. Try setting the `AWS_REGION` or `AWS_DEFAULT_REGION` environment variable.

**Comment by ravi-visionet** [comment]
> I missed this issue, apologies. You need to configure the AWS region. Try setting the `AWS_REGION` or `AWS_DEFAULT_REGION` environment variable.

Thank you, the mentioned issue is resolved now.
