### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by data-dude** [ribbybibby/s3_exporter#7]
I'm trying to connect to an internal s3 service and I configured the s3_endpoint_url but now i'm getting the error "certificate signed by unknown authority".  Has anyone been successful in running this with an internal s3 service?

**Comment by data-dude** [comment]
I found if you have the ca cert you can put them in the default location for ca certs and the go lang program will pick them up.
https://stackoverflow.com/questions/40051213/where-is-golang-picking-up-root-cas-from

**Comment by data-dude** [comment]
https://stackoverflow.com/questions/40051213/where-is-golang-picking-up-root-cas-from

**Comment by ribbybibby** [comment]
Hi @data-dude. Yep, the CA needs to be in the root certs on your system.
